services:
  frontend:
    # Frontend service configuration
    build:
      context: .
      dockerfile: Dockerfile
      args:
        # Build-time environment variables for the frontend
        - VITE_API_BASE_URL=${API_BASE_URL:-http://localhost:8000} # Base URL for the backend API
        - VITE_APP_VERSION=${APP_VERSION:-1.0.0} # Application version
    image: pixeletica/frontend:${TAG:-latest} # Docker image for the frontend
    container_name: pixeletica-frontend # Name of the frontend container
    restart: unless-stopped # Restart policy for the container
    ports:
      - '${FRONTEND_PORT:-3000}:3000' # Map host port to container port
    environment:
      # Runtime environment variables for the frontend
      - NODE_ENV=${NODE_ENV:-production} # Node.js environment
      - API_BASE_URL=${API_BASE_URL:-http://localhost:8000} # Base URL for the backend API
      - APP_VERSION=${APP_VERSION:-1.0.0} # Application version
      - DEFAULT_LOCALE=${DEFAULT_LOCALE:-en} # Default locale for the application
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro # Mount nginx configuration file
      - ${DATA_VOLUME:-./data}:/data # Volume for persistent data storage
    healthcheck:
      # Health check configuration for the frontend service
      test: ['CMD', 'wget', '-q', '--spider', 'http://localhost:3000/health'] # Command to check service health
      interval: 30s # Time between health checks
      timeout: 10s # Timeout for each health check
      retries: 3 # Number of retries before marking as unhealthy
      start_period: 10s # Initial delay before starting health checks
